name: Deploy

on:
  push:
    branches:
      - staging
      - production
  workflow_dispatch:

jobs:
  deploy:
    uses: itsemon245/gh-workflows/.github/workflows/push-to-cpanel.yml@main
    secrets: inherit
